# Generated by Django 3.2 on 2021-12-03 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='additional_file',
        ),
    ]
